language: haxe

haxe:
  - "3.2.1"
  - development

install:
  - git clone --recursive https://github.com/DoclerLabs/hexUnit.git ~/hexunit
  - git clone --recursive https://github.com/DoclerLabs/hexCore.git ~/hexcore
  - git clone --recursive https://github.com/DoclerLabs/hexInject.git ~/hexinject

script:
  - haxe build-js.hxml           && node bin/MainMVCTest.js
  
notifications:
  email:
    recipients:
      - francis_bourre@me.com
      - peterphonix@gmail.com