language: haxe

haxe:
  - "3.2.0"
  - development

matrix:
  # Allow Haxe development to fail.
  allow_failures:
    - haxe: development

addons:
  # This is the preferred way to install apt packages.
  # However, it only allow some but not all packages.
  # Alternatively, we can use `sudo apt-get install ...` in the `install:` section.
  # http://docs.travis-ci.com/user/apt/#Adding-APT-Packages
  apt:
    packages:
      # Python
      - python3
      # PHP
      - php5-cli
      # C#
      - mono-devel
      - mono-mcs
      # Flash
      - libcurl3:i386
      - libglib2.0-0:i386
      - libx11-6:i386
      - libxext6:i386
      - libxt6:i386
      - libxcursor1:i386
      - libnss3:i386
      - libgtk2.0-0:i386

install:
  - git clone --recursive https://github.com/aliokan/hexUnit.git dependencies/hexunit
  - git clone --recursive https://github.com/DoclerLabs/hexCore.git dependencies/hexcore
  - git clone --recursive https://github.com/DoclerLabs/hexInject.git dependencies/hexinject
  # os-specific config
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      export DISPLAY=:99.0;
      export AUDIODEV=null;
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update;
      brew install mono;
      brew install phantomjs;
      brew install python3;
    fi
  # Download and setup a standalone flash player debugger
  - haxe flash/install.hxml
  # Install haxelibs
  - haxelib install hxcpp
  - haxelib install hxjava
  - haxelib install hxcs
  - haxelib list

script:
  - haxe build-js.hxml           && node bin/MainMVCTest.js
  - haxe build-flash.hxml -D fdb && haxe flash/run.hxml bin/MainMVCTest.swf

notifications:
  email:
    recipients:
      - laurent@geturl.net
